wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    code_path: code/train_sweep.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1638293416
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.8
      5: 0.12.0
      8:
      - 3
      - 5
